version: '3'

services:
  srv:
    build: .
    command: flask run --host=0.0.0.0
    image: davidmnoll/flasknn
    volumes:
      - ./flasknn:/code
    ports:
      - "5000:5000"
      - "80:80"
    environment:
      - FLASK_DEBUG=1
